from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import Response
import requests
import json
import os

router = APIRouter()

# 🔑 REPLACE THIS WITH YOUR PDFSHIFT API KEY
PDFSHIFT_API_KEY = "sk_PLACEHOLDER" 

@router.post("/api/generate-pdf")
async def generate_pdf(form_data: dict):
    """
    Generates a PDF from the provided form data using PDFShift.
    """
    
    # 1. Construct HTML content from form data
    # We'll create a professional looking document template
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Application Form</title>
        <style>
            body {{
                font-family: 'Helvetica', 'Arial', sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 40px;
            }}
            .header {{
                text-align: center;
                border-bottom: 2px solid #333;
                padding-bottom: 20px;
                margin-bottom: 30px;
            }}
            .header h1 {{
                margin: 0;
                color: #2c3e50;
                font-size: 28px;
            }}
            .header p {{
                margin: 5px 0 0;
                color: #7f8c8d;
            }}
            .section {{
                margin-bottom: 25px;
                background: #f9f9f9;
                padding: 20px;
                border-radius: 8px;
                border: 1px solid #eee;
            }}
            .section-title {{
                font-size: 18px;
                font-weight: bold;
                color: #2c3e50;
                margin-bottom: 15px;
                border-bottom: 1px solid #ddd;
                padding-bottom: 5px;
            }}
            .field {{
                margin-bottom: 12px;
                display: flex;
                justify-content: space-between;
            }}
            .label {{
                font-weight: bold;
                color: #555;
                width: 40%;
            }}
            .value {{
                width: 55%;
                color: #000;
            }}
            .footer {{
                margin-top: 50px;
                text-align: center;
                font-size: 12px;
                color: #aaa;
                border-top: 1px solid #eee;
                padding-top: 20px;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Application Form</h1>
            <p>Generated by Seva Form AI</p>
        </div>
    """

    # Add Fields Dynamically
    html_content += '<div class="section"><div class="section-title">Applicant Details</div>'
    
    for key, value in form_data.items():
        # Format key to be readable (e.g., "first_name" -> "First Name")
        label = key.replace("_", " ").title()
        
        # Skip empty values if desired, or handle specific logic
        display_value = str(value) if value else "-"
        
        html_content += f"""
        <div class="field">
            <span class="label">{label}</span>
            <span class="value">{display_value}</span>
        </div>
        """
    
    html_content += '</div>' # End Section

    html_content += """
        <div class="footer">
            <p>This document was automatically generated. Please verify all details before official submission.</p>
        </div>
    </body>
    </html>
    """

    # 2. Call PDFShift API
    try:
        response = requests.post(
            "https://api.pdfshift.io/v3/convert/pdf",
            auth=("api", PDFSHIFT_API_KEY),
            json={
                "source": html_content,
                "landscape": False,
                "use_print": False,
                "sandbox": True # Remove this in production if needed
            }
        )

        response.raise_for_status()

        # 3. Return PDF Content
        return Response(
            content=response.content,
            media_type="application/pdf",
            headers={
                "Content-Disposition": "attachment; filename=application_form.pdf"
            }
        )

    except requests.exceptions.RequestException as e:
        print(f"PDFShift Error: {e}")
        if e.response:
            print(f"Response: {e.response.text}")
        raise HTTPException(status_code=500, detail="Failed to generate PDF")
